/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        // Brand
        'brand-navy': '#1E2A3A',
        'brand-orange': '#E79A4E',
        // Material tonal palette (from DESIGN.md)
        primary: '#8c4f03',
        'on-primary': '#ffffff',
        'primary-container': '#e79a4e',
        'on-primary-container': '#603400',
        'primary-fixed': '#ffdcc0',
        'primary-fixed-dim': '#ffb875',
        'on-primary-fixed': '#2d1600',
        'on-primary-fixed-variant': '#6b3b00',
        'inverse-primary': '#ffb875',
        secondary: '#535f71',
        'on-secondary': '#ffffff',
        'secondary-container': '#d7e3f9',
        'on-secondary-container': '#596577',
        'secondary-fixed': '#d7e3f9',
        'secondary-fixed-dim': '#bbc7dc',
        'on-secondary-fixed': '#101c2c',
        'on-secondary-fixed-variant': '#3c4859',
        tertiary: '#5e5e5b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#acaba7',
        'on-tertiary-container': '#3f403c',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f9f9ff',
        'on-background': '#151c27',
        surface: '#f9f9ff',
        'surface-dim': '#d3daea',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eefe',
        'surface-container-high': '#e2e8f8',
        'surface-container-highest': '#dce2f3',
        'on-surface': '#151c27',
        'on-surface-variant': '#524438',
        'surface-variant': '#dce2f3',
        'inverse-surface': '#2a313d',
        'inverse-on-surface': '#ebf1ff',
        outline: '#857466',
        'outline-variant': '#d8c3b3',
        'surface-tint': '#8c4f03',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'container-max': '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-md': ['Manrope', 'sans-serif'],
        'display-lg': ['Manrope', 'sans-serif'],
        'display-lg-mobile': ['Manrope', 'sans-serif'],
        'headline-md-mobile': ['Manrope', 'sans-serif'],
        'title-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '800' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      boxShadow: {
        custom: '0px 4px 20px rgba(30, 42, 58, 0.08)',
        'custom-hover': '0px 12px 32px rgba(30, 42, 58, 0.12)',
        soft: '0px 4px 20px rgba(30, 42, 58, 0.08)',
      },
    },
  },
  plugins: [],
};
